version: '3.3'

services:
  datebase:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myPassword
    expose:
      - 5432
  backend:
    container_name: moneytransferservice
    build: .
